---
# tasks file for backup_config
- name: BACKUP THE IOS CONFIG
  # ios_config and nxos_config works for ios/nxos for backup  
  ios_config:
    backup: yes
  register: config_output

- name: RENAME BACKUP
  copy:
    src: "{{config_output.backup_path}}"
    dest: "{{dest_dir}}/{{inventory_hostname}}"

- name: RENAME OLD BACKUP FILE 
  file:
    state: absent 
    path: "{{config_output.backup_path}}"
    
- name: REMOVE NON CONFIG LINES
  lineinfile:
    path: "{{dest_dir}}/{{inventory_hostname}}"
    line: "Building configuration..."
    state: absent

- name: REMOVE NON CONFIG LINES - REGEXP
  lineinfile:
    path: "{{dest_dir}}/{{inventory_hostname}}"
    regexp: 'Current configuration.*'
    state: absent 